# Downloads Inter and Material Symbols woff2 files and generates local-fonts.css
$fontsDir = Join-Path $PSScriptRoot "..\public\fonts"
$cssOut = Join-Path $PSScriptRoot "..\public\css\local-fonts.css"
if (-not (Test-Path $fontsDir)) { New-Item -ItemType Directory -Path $fontsDir -Force | Out-Null }

$families = @(
    "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap",
    "https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap"
)

$collectedCss = "/* local-fonts.css - generated by download-fonts.ps1 */`n"
foreach ($url in $families) {
    Write-Host "Fetching: $url"
    try {
        $css = (Invoke-RestMethod -Uri $url -UseBasicParsing -ErrorAction Stop)
    } catch {
        Write-Error "Failed to fetch $url : $_"
        continue
    }
    # Find all remote font URLs
    $matches = [regex]::Matches($css, "url\((https://[^)]+)\)")
    foreach ($m in $matches) {
        $fontUrl = $m.Groups[1].Value
        $leaf = [System.Uri]::new($fontUrl).Segments[-1]
        $dest = Join-Path $fontsDir $leaf
        if (-not (Test-Path $dest)) {
            Write-Host "Downloading $fontUrl -> $leaf"
            try {
                Invoke-WebRequest -Uri $fontUrl -OutFile $dest -UseBasicParsing -ErrorAction Stop
            } catch {
                Write-Error "Failed to download $fontUrl : $_"
            }
        } else {
            Write-Host "Already exists: $leaf"
        }
        # Replace remote URL in CSS with local path
        $css = $css -replace [regex]::Escape($fontUrl), ("/fonts/" + $leaf)
    }
    $collectedCss += $css + "`n"
}

# Write combined local CSS
Write-Host "Writing local CSS to $cssOut"
Set-Content -Path $cssOut -Value $collectedCss -Encoding UTF8
Write-Host "Done. Fonts saved to: $fontsDir"
Write-Host "If you want the site to use only local fonts, ensure /css/global-font.css imports /css/local-fonts.css first (already configured)."